version: '3.8'

services:
  web:
    container_name: Django
    build: .
    image: django-img
    command: python manage.py runsslserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev